on:
  push:
    branches:
      - "*"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Build binary
        run: make all

      - name: Copy out example bat
        run: cp examples/go-miner-*.bat .

      - uses: actions/upload-artifact@v2
        with:
          path: |
            bin/go-miner-*
            README.md

  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Run basic commands
        run: |
          mv artifact/bin .
          chmod a+x bin/go-miner-linux-386
          bin/go-miner-linux-386 -h
          bin/go-miner-linux-386 -version
          chmod a+x bin/go-miner-linux-amd64
          bin/go-miner-linux-amd64 -h
          bin/go-miner-linux-amd64 -version

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Move bins
        run: |
          mv artifact/bin .
      - name: Run basic commands - 64 Bit
        run: |
          bin/go-miner-windows-amd64 -h
          bin/go-miner-windows-amd64 -version
      - name: Run basic commands - 32 Bit
        run: |
          bin/go-miner-windows-386 -h
          bin/go-miner-windows-386 -version

  test-macos:
    name: Test Mac OS
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Move bins
        run: |
          mv artifact/bin .
      - name: Run basic commands
        run: |
          chmod a+x bin/go-miner-darwin-amd64
          bin/go-miner-darwin-amd64 -h
          bin/go-miner-darwin-amd64 -version

  test-arm:
    name: Test ARM
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Move bins
        run: |
          mv artifact/bin .
      - name: Run basic commands
        run: |
          sh -c 'if test -f "bin/go-miner-linux-arm"; then echo "ARM binary found"; else echo "ARM binary not found" && exit 1; fi'
          sh -c 'if test -f "bin/go-miner-linux-arm64"; then echo "ARM64 binary found"; else echo "ARM64 binary not found" && exit 1; fi'

  package-release:
    if: contains(github.ref, '/tags/v')
    name: Package and Upload
    runs-on: ubuntu-latest
    needs: [build, test-linux, test-windows, test-macos, test-arm]
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Move bins
        run: |
          mv artifact/bin/* bin/
      - name: Package
        run: make packages
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/go-miner*.zip
            packages/go-miner*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
