on:
  push:
    branches:
      - "*"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Build binary
        run: make all

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            go-miner*
            payment-requestor*
            README.md

  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Run -h
        run: |
          chmod a+x binaries/go-miner-linux
          binaries/go-miner-linux -h

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Run -h
        run: |
          binaries/go-miner.exe -h

  test-macos:
    name: Test Mac OS
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Run -h
        run: |
          chmod a+x binaries/go-miner-macos
          binaries/go-miner-macos -h

  cut-release:
    if: contains(github.ref, '/tags/v')
    name: Package and Upload
    runs-on: ubuntu-latest
    needs: [build, test-linux, test-windows, test-macos]
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: Package
        run: make zip
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            go-miner*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
